import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="navigationBar">
          <a href="/">Sustainment</a>
          <a href="/discover">Discover</a>
          <a href="/about">About</a>
          <a href="/login">Login</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
